# Lesson 13: NumPy

Learn the foundation of scientific computing in Python — NumPy arrays.

In [1]:
import numpy as np

## Creating Arrays

In [2]:
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
eye = np.eye(3)
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)
random = np.random.randn(3, 3)

print(f"1D: {arr1d}")
print(f"2D:\n{arr2d}")
print(f"Zeros shape: {zeros.shape}")

1D: [1 2 3 4 5]
2D:
[[1 2 3]
 [4 5 6]]
Zeros shape: (3, 4)


## Array Attributes

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array:\n{arr}")
print(f"Shape: {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"Size: {arr.size}")
print(f"Dtype: {arr.dtype}")

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Dtype: int64


## Indexing and Slicing

In [4]:
matrix = np.arange(9).reshape(3, 3)
print(f"Matrix:\n{matrix}")
print(f"Element [1,2]: {matrix[1, 2]}")
print(f"First row: {matrix[0]}")
print(f"Last col: {matrix[:, -1]}")
print(f"Submatrix:\n{matrix[:2, :2]}")
print(f"Boolean: {matrix[matrix > 4]}")

Matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Element [1,2]: 5
First row: [0 1 2]
Last col: [2 5 8]
Submatrix:
[[0 1]
 [3 4]]
Boolean: [5 6 7 8]


## Universal Functions

In [5]:
arr = np.array([1, 4, 9, 16, 25])
print(f"Original: {arr}")
print(f"sqrt: {np.sqrt(arr)}")
print(f"log: {np.log(arr)}")
print(f"+ 10: {arr + 10}")
print(f"* 2: {arr * 2}")

Original: [ 1  4  9 16 25]
sqrt: [1. 2. 3. 4. 5.]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
+ 10: [11 14 19 26 35]
* 2: [ 2  8 18 32 50]


## Broadcasting

In [6]:
matrix = np.ones((4, 3))
vector = np.array([1, 2, 3])
result = matrix + vector
print(f"Matrix:\n{matrix}")
print(f"Vector: {vector}")
print(f"Result:\n{result}")

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Vector: [1 2 3]
Result:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


## Linear Algebra

In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(f"A @ B:\n{a @ b}")
print(f"Inverse A:\n{np.linalg.inv(a)}")
print(f"Det A: {np.linalg.det(a)}")

A @ B:
[[19 22]
 [43 50]]
Inverse A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Det A: -2.0000000000000004


## Biotechnology Example

In [8]:
np.random.seed(42)
expression = np.random.randn(5, 4) * 2 + 5
genes = ["BRCA1", "TP53", "EGFR", "MYC", "KRAS"]

means = expression.mean(axis=1).reshape(-1, 1)
stds = expression.std(axis=1).reshape(-1, 1)
z_scores = (expression - means) / stds

for i, gene in enumerate(genes):
    print(f"{gene}: mean={expression[i].mean():.2f}, z-scores={z_scores[i].round(2)}")

BRCA1: mean=6.26, z-scores=[-0.23 -1.3   0.03  1.5 ]
TP53: mean=5.94, z-scores=[-0.93 -0.93  1.46  0.39]
EGFR: mean=4.57, z-scores=[-0.58  1.73 -0.57 -0.58]
MYC: mean=3.02, z-scores=[ 1.4  -1.05 -0.84  0.49]
KRAS: mean=3.49, z-scores=[-0.4   1.66 -0.24 -1.02]


## SaaS Example

In [9]:
np.random.seed(42)
dau = np.random.randint(1000, 5000, size=(7, 3))
products = ["Dashboard", "Analytics", "Reports"]

for i, p in enumerate(products):
    print(f"{p}: {dau[:, i].mean():.0f} ± {dau[:, i].std():.0f}")

corr = np.corrcoef(dau.T)
print(f"Correlation:\n{corr}")

Dashboard: 3560 ± 1238
Analytics: 2854 ± 1285
Reports: 2653 ± 649
Correlation:
[[1.         0.35389583 0.07917532]
 [0.35389583 1.         0.18556647]
 [0.07917532 0.18556647 1.        ]]


## Summary
- ndarray: fast, homogeneous, multidimensional
- Vectorized operations = C speed
- Broadcasting: flexible shape operations
- Universal functions: element-wise math
- Linear algebra: @, linalg
- Foundation for Pandas, scikit-learn

## Exercises

1. **Basic**: Write a short program that demonstrates the concepts covered in this lesson.
2. **Practice**: Modify the examples to work with different inputs.
3. **Challenge**: Combine this lesson's concepts with what you learned in previous lessons.
